spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.223.65.182:3306/LLDrive
      username: LLDrive
      password: LLDrive

    mail:
      host: smtp.163.com
      username: LLDrive@163.com
      password: STQNFPPOAXQFJKFF
      protocol: smtp
server:
  port: 8848