spring:
    devtools:
      restart:
        enabled: true
        additional-paths: src/main/java
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username:
      password:

    mail:
      host:
      username:
      password:
      protocol:
server:
  port: 8848